# netlify.toml

[build]
  # 如果你的站点是用 npm run build 打包到 build/
  command   = "npm run build"
  publish   = "build"                 # ← 这里从 public 改成 build
  functions = "netlify/functions"     # 确保你的函数目录没填错

[[redirects]]
  from   = "/admin/*"
  to     = "/admin/index.html"
  status = 200
