// sidebars.ts
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 自动把 docs/ 下面的所有子目录视为一级分类
    },
  ],
};

export default sidebars;
